"""empty message

Revision ID: 176e13636427
Revises: 1f7e817cf683
Create Date: 2017-08-19 12:17:29.726854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176e13636427'
down_revision = '1f7e817cf683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
