"""empty message

Revision ID: 97431d510e6d
Revises: 176e13636427
Create Date: 2017-08-19 12:55:14.828233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97431d510e6d'
down_revision = '176e13636427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patients_id_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('users_gender_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'genders', ['gender_id'], ['gender_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_gender_id_fkey', 'users', 'genders', ['gender_id'], ['gender_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_id_fkey', 'patients', 'users', ['id'], ['id'])
    # ### end Alembic commands ###
